FROM ubuntu:24.04


ARG COUNTRY
ARG HTTP_PROXY
ARG HTTPS_PROXY
ARG ALL_PROXY
ARG NODE_VERSION



RUN apt update && apt install -y --no-install-recommends dirmngr ca-certificates apt-transport-https

#China only
RUN if [ "$COUNTRY" = "CHINA" ] ; then echo>/etc/apt/sources.list; echo>/etc/apt/sources.list.d/ubuntu.sources; printf "deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble main restricted universe multiverse\n\
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-updates main restricted universe multiverse\n\
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-backports main restricted universe multiverse\n\
deb http://security.ubuntu.com/ubuntu/ noble-security main restricted universe multiverse\n" >/etc/apt/sources.list ;fi



RUN apt -y update
RUN apt -y install git curl build-essential python3 python-is-python3 python3-setuptools npm

RUN mkdir -p /opt
WORKDIR /opt


# install nvm
RUN curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh -o /tmp/install_nvm.sh && bash /tmp/install_nvm.sh

# set env
ENV NVM_DIR=/root/.nvm
ENV NODE_VERSION=${NODE_VERSION}
ENV DATABASE_URL=mysql://am32:am32@127.0.0.1:3306/am32

# install node
RUN bash -c "source $NVM_DIR/nvm.sh && nvm install $NODE_VERSION && nvm alias default $NODE_VERSION"

COPY  --chown=root:root --chmod=700  build-common.sh am32-conf-master.sh .

RUN ./am32-conf-master.sh

WORKDIR /opt/am32-configurator

# set ENTRYPOINT for reloading nvm-environment
ENTRYPOINT ["bash", "-c", "source $NVM_DIR/nvm.sh && nvm use \"$NODE_VERSION\" >/dev/null && exec \"$@\"", "--"]
