FROM ubuntu:24.04

ARG COUNTRY


RUN apt update && apt install -y --no-install-recommends dirmngr ca-certificates apt-transport-https

#China only
RUN if [ "$COUNTRY" = "CHINA" ] ; then echo>/etc/apt/sources.list; echo>/etc/apt/sources.list.d/ubuntu.sources; printf "deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble main restricted universe multiverse\n\
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-updates main restricted universe multiverse\n\
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-backports main restricted universe multiverse\n\
deb http://security.ubuntu.com/ubuntu/ noble-security main restricted universe multiverse\n" >/etc/apt/sources.list ;fi



RUN apt -y update
RUN apt -y full-upgrade
RUN apt -y install build-essential git curl clang-18 python3 python-is-python3

RUN mkdir -p /opt /fw
WORKDIR /opt
