FROM ubuntu:24.04


ARG COUNTRY
ARG HTTP_PROXY
ARG HTTPS_PROXY
ARG ALL_PROXY
ARG BETAFLIGHT_VERSION
ARG BETAFLIGHT_BRANCH
ARG BB_VER



RUN apt update && apt install -y --no-install-recommends dirmngr ca-certificates apt-transport-https

#China only
RUN if [ "$COUNTRY" = "CHINA" ] ; then echo>/etc/apt/sources.list; echo>/etc/apt/sources.list.d/ubuntu.sources; printf "deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble main restricted universe multiverse\n\
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-updates main restricted universe multiverse\n\
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-backports main restricted universe multiverse\n\
deb http://security.ubuntu.com/ubuntu/ noble-security main restricted universe multiverse\n" >/etc/apt/sources.list ;fi



RUN apt -y update
RUN apt -y full-upgrade
RUN apt -y install git curl python3 python-is-python3 npm

RUN mkdir -p /opt
WORKDIR /opt


# install nvm
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash

# set env
ENV NVM_DIR=/root/.nvm

COPY  --chown=root:root --chmod=700  bb.sh .

RUN ./bb.sh

WORKDIR /opt/blackbox-log-viewer

# set ENTRYPOINT for reloading nvm-environment
ENTRYPOINT ["bash", "-c", "source $NVM_DIR/nvm.sh && exec \"$@\"", "--"]
