server {
  listen 80;

  root /usr/share/nginx/html;
  index index.html;

  add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" always;
  add_header Pragma "no-cache" always;
  add_header Expires "0" always;

  location = /sw.js {
    add_header Clear-Site-Data "\"cache\", \"storage\"" always;
    add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" always;
    return 410;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }

  error_page 500 502 503 504 /50x.html;

  location = /50x.html {
    root /usr/share/nginx/html;
  }

  large_client_header_buffers 4 32k;
}
