---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services

- Configurators:
    - Betaflight Configurator:
        icon: npm.png
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:82
        description: "tag: {{HOMEPAGE_VAR_BETAFLIGHT_CONF_VERSION}}"
    - Betaflight Configurator Master:
        icon: npm.png
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:88
        description: "branch: master"
    - AM32 Configurator Master:
        icon: npm.png
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:89
        description: "branch: master"
    - ESC Configurator:
        icon: npm.png
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:83
        description:
    - Blackbox Log Viewer:
        icon: npm.png
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:85
        description:
    - ELRS Web Flasher:
        icon: npm.png
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:84
        description:
    # - Bucksaw:
    #     icon: nginx.png
    #     href: http://{{HOMEPAGE_VAR_HOST_IP}}:90
    #     description: "WebAssembly app"
    - ELRS Configurator (mainly for compiling MurmurLRS):
        icon: guacamole.png
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:91
        description: "guacadmin:guacadmin, expert mode, select local source: /firmware/MurmurLRS/src . the compiled firmware will be in host's elrs-firmware-src/MurmurLRS/src/.pio/build/"

- Files:
    - download the files:
        icon: nginx.png
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:86
        description: "current betaflight {{HOMEPAGE_VAR_BETAFLIGHT_VERSION}}, target {{HOMEPAGE_VAR_BETAFLIGHT_FW_TARGET}}. current Bluejay {{HOMEPAGE_VAR_BLUEJAY_VERSION}}, target {{HOMEPAGE_VAR_BLUEJAY_TARGET}}, PWM {{HOMEPAGE_VAR_BLUEJAY_PWM}} kHz. "
